In [1]:
import json
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
import warnings
from collections import Counter
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import MinMaxScaler
import joblib
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.svm import LinearSVC
from sklearn.ensemble import VotingClassifier
from sklearn.calibration import CalibratedClassifierCV

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/satssehgal/MLAPLI/master/bankloan.csv')
df=df.dropna()
df.isna().any()
df=df.drop('Loan_ID', axis=1)
df['LoanAmount']=(df['LoanAmount']*1000).astype(int)
Counter(df['Loan_Status'])

Counter({'N': 148, 'Y': 332})

In [3]:
y_pre = df['Loan_Status']
x_pre = df.drop('Loan_Status', axis=1)
dm_x = pd.get_dummies(x_pre)
dm_y = y_pre.map(dict(Y=1, N=0))
dm_x

,Dependents,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Gender_Female,Gender_Male,Married_No,Married_Yes,Education_Graduate,Education_Not Graduate,Self_Employed_No,Self_Employed_Yes,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
1,1.0,4583,1508.0,128000,360.0,1.0,0,1,0,1,1,0,1,0,1,0,0
2,0.0,3000,0.0,66000,360.0,1.0,0,1,0,1,1,0,0,1,0,0,1
3,0.0,2583,2358.0,120000,360.0,1.0,0,1,0,1,0,1,1,0,0,0,1
4,0.0,6000,0.0,141000,360.0,1.0,0,1,1,0,1,0,1,0,0,0,1
5,2.0,5417,4196.0,267000,360.0,1.0,0,1,0,1,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,0.0,2900,0.0,71000,360.0,1.0,1,0,1,0,1,0,1,0,1,0,0
610,3.0,4106,0.0,40000,180.0,1.0,0,1,0,1,1,0,1,0,1,0,0
611,1.0,8072,240.0,253000,360.0,1.0,0,1,0,1,1,0,1,0,0,0,1
612,2.0,7583,0.0,187000,360.0,1.0,0,1,0,1,1,0,1,0,0,0,1
613,0.0,4583,0.0,133000,360.0,0.0,1,0,1,0,1,0,0,1,0,1,0

In [4]:
smote = SMOTE(sampling_strategy='minority')
x1, y = smote.fit_sample(dm_x, dm_y)
sc = MinMaxScaler()
x = sc.fit_transform(x1)

In [5]:
Counter(y)

Counter({0: 332, 1: 332})

In [6]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.25, random_state=1234)

In [7]:
rf = RandomForestClassifier(n_estimators = 100)
rf = rf.fit(X_train, y_train)

In [8]:
et = ExtraTreesClassifier(n_estimators = 100)
et = et.fit(X_train, y_train)

In [9]:
mnb = MultinomialNB()
mnb = mnb.fit(X_train, y_train)

In [10]:
lr=LogisticRegression(max_iter=1000)
lr = lr.fit(X_train, y_train)

In [11]:
svc= svm.SVC(kernel='linear',probability=True)
svc = svc.fit(X_train,y_train)

In [12]:
evc=VotingClassifier(estimators=[('mnb', mnb),('lr', lr),('rf', rf),('et', et)],voting='soft')
evc = evc.fit(X_train, y_train)

array([[0.17427648, 0.82572352],
       [0.18276364, 0.81723636],
       [0.32287838, 0.67712162],
       [0.76389665, 0.23610335],
       [0.530895  , 0.469105  ],
       [0.21718181, 0.78281819],
       [0.25516575, 0.74483425],
       [0.90069597, 0.09930403],
       [0.58169472, 0.41830528],
       [0.30989895, 0.69010105],
       [0.15750196, 0.84249804],
       [0.7491731 , 0.2508269 ],
       [0.2489506 , 0.7510494 ],
       [0.68432698, 0.31567302],
       [0.12017056, 0.87982944],
       [0.88948923, 0.11051077],
       [0.85432255, 0.14567745],
       [0.26351032, 0.73648968],
       [0.37240049, 0.62759951],
       [0.40515355, 0.59484645],
       [0.89153447, 0.10846553],
       [0.81276749, 0.18723251],
       [0.88412002, 0.11587998],
       [0.83389118, 0.16610882],
       [0.27302287, 0.72697713],
       [0.29518755, 0.70481245],
       [0.86000921, 0.13999079],
       [0.2470557 , 0.7529443 ],
       [0.20972784, 0.79027216],
       [0.29555433, 0.70444567],
       [0.82849023, 0.17150977],
       [0.87462577, 0.12537423],
       [0.89473512, 0.10526488],
       [0.19425272, 0.80574728],
       [0.5127788 , 0.4872212 ],
       [0.33772318, 0.66227682],
       [0.87676007, 0.12323993],
       [0.50136996, 0.49863004],
       [0.4004404 , 0.5995596 ],
       [0.85106466, 0.14893534],
       [0.5443564 , 0.4556436 ],
       [0.45323164, 0.54676836],
       [0.3049314 , 0.6950686 ],
       [0.67007399, 0.32992601],
       [0.26373269, 0.73626731],
       [0.18628867, 0.81371133],
       [0.5440691 , 0.4559309 ],
       [0.89323421, 0.10676579],
       [0.24112347, 0.75887653],
       [0.79258961, 0.20741039],
       [0.91363588, 0.08636412],
       [0.36822319, 0.63177681],
       [0.28974215, 0.71025785],
       [0.50638775, 0.49361225],
       [0.87803588, 0.12196412],
       [0.1437    , 0.8563    ],
       [0.20260365, 0.79739635],
       [0.8438031 , 0.1561969 ],
       [0.23742366, 0.76257634],
       [0.85699442, 0.14300558],
       [0.86662835, 0.13337165],
       [0.22730516, 0.77269484],
       [0.13847479, 0.86152521],
       [0.90006693, 0.09993307],
       [0.46391511, 0.53608489],
       [0.84387694, 0.15612306],
       [0.1976136 , 0.8023864 ],
       [0.21348023, 0.78651977],
       [0.79489485, 0.20510515],
       [0.76610427, 0.23389573],
       [0.89311081, 0.10688919],
       [0.69446509, 0.30553491],
       [0.77888004, 0.22111996],
       [0.12763505, 0.87236495],
       [0.23461775, 0.76538225],
       [0.84042354, 0.15957646],
       [0.25020756, 0.74979244],
       [0.50890432, 0.49109568],
       [0.19506942, 0.80493058],
       [0.73288006, 0.26711994],
       [0.37492707, 0.62507293],
       [0.53664944, 0.46335056],
       [0.83466219, 0.16533781],
       [0.20088201, 0.79911799],
       [0.19088244, 0.80911756],
       [0.84693115, 0.15306885],
       [0.19808405, 0.80191595],
       [0.30055481, 0.69944519],
       [0.82839386, 0.17160614],
       [0.21013314, 0.78986686],
       [0.35200548, 0.64799452],
       [0.89256863, 0.10743137],
       [0.1694737 , 0.8305263 ],
       [0.38842443, 0.61157557],
       [0.19984502, 0.80015498],
       [0.71279387, 0.28720613],
       [0.75531242, 0.24468758],
       [0.87859229, 0.12140771],
       [0.8888851 , 0.1111149 ],
       [0.78185355, 0.21814645],
       [0.27404944, 0.72595056],
       [0.12971916, 0.87028084],
       [0.90388379, 0.09611621],
       [0.12099895, 0.87900105],
       [0.89867667, 0.10132333],
       [0.88426686, 0.11573314],
       [0.33055269, 0.66944731],
       [0.35219435, 0.64780565],
       [0.87308692, 0.12691308],
       [0.10456618, 0.89543382],
       [0.27363878, 0.72636122],
       [0.16404519, 0.83595481],
       [0.23378896, 0.76621104],
       [0.43439394, 0.56560606],
       [0.39188681, 0.60811319],
       [0.76456352, 0.23543648],
       [0.29927322, 0.70072678],
       [0.2755374 , 0.7244626 ],
       [0.17515905, 0.82484095],
       [0.89308669, 0.10691331],
       [0.79773003, 0.20226997],
       [0.29802321, 0.70197679],
       [0.64299989, 0.35700011],
       [0.29433143, 0.70566857],
       [0.37304044, 0.62695956],
       [0.26768275, 0.73231725],
       [0.20350625, 0.79649375],
       [0.80232006, 0.19767994],
       [0.29361879, 0.70638121],
       [0.18105044, 0.81894956],
       [0.18219828, 0.81780172],
       [0.91170109, 0.08829891],
       [0.27736965, 0.72263035],
       [0.12895436, 0.87104564],
       [0.87041416, 0.12958584],
       [0.30630716, 0.69369284],
       [0.88582597, 0.11417403],
       [0.27537718, 0.72462282],
       [0.29550317, 0.70449683],
       [0.18170556, 0.81829444],
       [0.76858173, 0.23141827],
       [0.21808459, 0.78191541],
       [0.30919253, 0.69080747],
       [0.55014695, 0.44985305],
       [0.76616234, 0.23383766],
       [0.29461794, 0.70538206],
       [0.30575825, 0.69424175],
       [0.20589858, 0.79410142],
       [0.63071789, 0.36928211],
       [0.57429573, 0.42570427],
       [0.2272585 , 0.7727415 ],
       [0.68240044, 0.31759956],
       [0.28533739, 0.71466261],
       [0.13617325, 0.86382675],
       [0.26307804, 0.73692196],
       [0.16555397, 0.83444603],
       [0.23618936, 0.76381064],
       [0.3739088 , 0.6260912 ],
       [0.88949854, 0.11050146],
       [0.84308591, 0.15691409],
       [0.20891373, 0.79108627],
       [0.25361268, 0.74638732],
       [0.20303817, 0.79696183],
       [0.39762396, 0.60237604],
       [0.16414481, 0.83585519],
       [0.09921809, 0.90078191]])

In [13]:
joblib.dump(rf, "./random_forest.joblib", compress=True)
joblib.dump(et, "./extra_trees.joblib", compress=True)
joblib.dump(mnb, "./naive_bayes.joblib", compress=True)
joblib.dump(lr, "./logistic_regression.joblib", compress=True)
joblib.dump(svc, "./support_vector_machine.joblib", compress=True)
joblib.dump(evc, "./voting_classifier.joblib", compress=True)

['./voting_classifier.joblib']

In [14]:
train_mode = dict(df.mode().iloc[0])
print(train_mode)

{'Gender': 'Male', 'Married': 'Yes', 'Dependents': 0.0, 'Education': 'Graduate', 'Self_Employed': 'No', 'ApplicantIncome': 2500.0, 'CoapplicantIncome': 0.0, 'LoanAmount': 100000, 'Loan_Amount_Term': 360.0, 'Credit_History': 1.0, 'Property_Area': 'Semiurban', 'Loan_Status': 'Y'}